name: Build

on:
  push:
    branches-ignore: 
      - master

jobs:
  BuildRunTests:
    runs-on: windows-latest
    steps:
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v2
    - name: download nuget
      uses: nuget/setup-Nuget@v1
    - name: restore nuget packages
      run: nuget.exe restore Src\MongoLinqPlusPlus.sln
    - name: build solution
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Src\MongoLinqPlusPlus.sln
      shell: cmd
    - name: run tests
      run: dotnet test .\Src\UnitTests\UnitTests.csproj
