name: Build

on:
  push:
    branches-ignore: 
      - master

jobs:
  BuildRunTestsAndPublishNuget:
    runs-on: windows-latest
    steps:
    - name: download mongo
      run: choco install mongodb --version 4.4.1 -my
    - name: check log
      run: |
        gc C:\ProgramData\chocolatey\logs\chocolatey.log | more
      shell: powershell
      if: ${{ always() }}
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v2
    - name: download nuget
      uses: nuget/setup-Nuget@v1
    - name: restore nuget packages
      run: nuget.exe restore Src\MongoLinqPlusPlus.sln
    - name: build solution
      run: |
        dotnet test Src\UnitTests\bin\Debug\netcoreapp3.1\UnitTests.dll
      shell: cmd
    - name: run tests
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\mstest.exe" /testcontainer:Src\UnitTests\bin\Debug\netcoreapp3.1\UnitTests.dll
      shell: cmd
