name: Build

on:
  push:
    branches-ignore: 
      - master

jobs:
  BuildRunTestsAndPublishNuget:
    runs-on: windows-latest
    steps:
    - name: download mongo
      run: |
        echo "choco install mongodb --version 4.2.0 -my"
        choco install mongodb --version 4.2.0 -my
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v2
    - name: download nuget
      uses: nuget/setup-Nuget@v1
    - name: restore nuget packages
      run: nuget.exe restore Src\MongoLinqPlusPlus.sln
    - name: build solution
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Src\MongoLinqPlusPlus.sln
      shell: cmd
    - name: run tests
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\mstest.exe" /testcontainer:Src\UnitTests\bin\Debug\netcoreapp3.1\UnitTests.dll
      shell: cmd
