name: MasterPublish

on:
  push:
    branches: 
      - master

jobs:
  BuildRunTestsAndPublishNuget:
    runs-on: windows-latest
    steps:
    # Checkout code from repo
    
    - name: checkout repo
      uses: actions/checkout@v2  
    
    - name: download nuget
      uses: nuget/setup-Nuget@v1
      
    - name: restore nuget packages
      run: nuget.exe restore Src\MongoLinqPlusPlus.sln
      
    - name: build solution
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Src\MongoLinqPlusPlus.sln
      shell: cmd
    
    - name: Start MongoDB
      shell: pwsh
      run: |
          Set-Service mongodb -StartupType Automatic
          Start-Service -Name mongodb
          
    - name: run tests
      run: dotnet test .\Src\UnitTests\UnitTests.csproj
      
    - name: Print new build number
      run: echo Build number is $GITHUB_RUN_NUMBER
      shell: bash
      
    - name: Setup Nuget and Push Package
      run: |
        nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/pathmatics/index.json" -UserName pathmatics -Password ${{ secrets.GITHUB_TOKEN }}
        nuget pack Src/MongoLinqPlusPlus/MongoLinqPlusPlus.csproj -Version $GITHUB_RUN_NUMBER
        nuget setapikey ${{ secrets.GITHUB_TOKEN }} -Source "GitHub"
        nuget push *.nupkg -Source "GitHub" -SkipDuplicate
      shell: bash
      
      
