name: MasterPublish

on:
  push:
    branches: 
      - master

jobs:
  BuildRunTestsAndPublishNuget:
    runs-on: windows-latest
    steps:
    # Checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v2
    - name: download nuget
      uses: nuget/setup-Nuget@v1
    - name: restore nuget packages
      run: nuget.exe restore Src\MongoLinqPlusPlus.sln
    - name: build solution
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Src\MongoLinqPlusPlus.sln
      shell: cmd
    - name: run tests
      run: dotnet test .\Src\UnitTests\UnitTests.csproj
    - name: Generate build number
      uses: einaregilsson/build-number@v1 
      with:
        token: ${{secrets.GITHUB_TOKEN}}        
    - name: Print new build number
      run: echo Build number is $BUILD_NUMBER - ${{ steps.buildnumber.outputs.build_number }}
      shell: bash
    - name: Setup Nuget and Push Package
      run: |
        nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/pathmatics/index.json" -UserName pathmatics -Password ${{ secrets.GITHUB_TOKEN }}
        nuget pack Src/MongoLinqPlusPlus/MongoLinqPlusPlus.csproj -Version $BUILD_NUMBER
        nuget setapikey ${{ secrets.GITHUB_TOKEN }} -Source "GitHub"
        nuget push *.nupkg -Source "GitHub" -SkipDuplicate
      shell: bash
